# Generated by Django 2.2.12 on 2021-10-30 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=40)),
                ('titile', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('pages', models.PositiveIntegerField()),
            ],
        ),
    ]
